### ISSUE TITLE
增加导出登录用户权限代码功能

### ISSUE THREAD

**Issue by wayshall** [wayshall/zifish-plugins#1]
增加导出登录用户权限代码功能

**Comment by wayshall** [comment]
配置如下
```yaml
jfish: 
    plugin:
        web-admin:
            loginUser: 
                exposeAuthorities: true
```
配置后，访问/me api会增加一个authorities属性，表示权限集
